// Font Awesome Icons
import {
  FaArrowLeft,
  FaArrowRight,
  FaAward,
  FaBell,
  FaBookmark,
  FaBriefcase,
  FaBuilding,
  FaBullhorn,
  FaBullseye,
  FaCalendarAlt,
  FaCalendarDay,
  FaChartLine,
  FaCheck,
  FaChevronLeft,
  FaChevronRight,
  FaClipboardList,
  FaClock,
  FaEdit,
  FaEnvelope,          // ✉️ أيقونة الرسالة
  FaExclamationCircle,
  FaExclamationTriangle,
  FaEye,
  FaFacebookF,
  FaFilter,
  FaGavel,
  FaGlobe,
  FaHandshake,
  FaHeart,
  FaHome,
  FaImage,
  FaInstagram,
  FaLandmark,
  FaLinkedinIn,
  FaList,
  FaListAlt,
  FaMapMarked,
  FaMapMarkerAlt,
  FaMoneyBillWave,
  FaPaperPlane,        // 📨 أيقونة إرسال / Mission
  FaPhone,
  FaPlus,
  FaReact,
  FaRedo,
  FaRulerCombined,
  FaSearch,
  FaSearchDollar,
  FaShare,
  FaShieldAlt,
  FaSignOutAlt,
  FaSnapchatGhost,
  FaStar,
  FaTag,
  FaTimes,
  FaTrash,
  FaTwitter,
  FaUser,
  FaUsers,
  FaWhatsapp,
  FaYoutube,
  FaTiktok,
  FaFileContract,
  FaGem,           // إضافة هذا السطر
  FaCrown,         // إضافة هذا السطر
  FaBrain,         // إضافة هذا السطر
  FaNetworkWired,  // إضافة هذا السطر
  FaCheckCircle,
  FaUpload, 
  FaFileAlt,
  FaBan,
  FaRegClock,
  FaRegFileAlt,
  
} from "react-icons/fa";

// Feather Icons
import {
  FiBriefcase,
  FiCheckCircle,
  FiClock,
  FiDollarSign,
  FiFileText,
  FiHome,
  FiMail,
  FiPhone,
  FiUser,
  FiArrowRight,
  FiLogIn,
  FiXCircle,
  FiLock, FiEye, FiEyeOff, FiX, FiArrowLeft,
  FiFile, FiBook,
  FiCheck
} from "react-icons/fi";

// Material Design Icons
import {
  MdAssignment,
  MdBadge,
  MdBusiness,
  MdPerson
} from "react-icons/md";

// 🔹 تصدير جميع الأيقونات في Object واحد
const Icons = {
  // FA
  FaCheckCircle,
  FaGem,           // إضافة هذا السطر
  FaCrown,         // إضافة هذا السطر
  FaBrain,         // إضافة هذا السطر
  FaNetworkWired,  // إضافة هذا السطر
  FaArrowLeft,
  FaArrowRight,
  FaAward,
  FaBell,
  FaBookmark,
  FaBriefcase,
  FaBuilding,
  FaBullhorn,
  FaBullseye,
  FaCalendarAlt,
  FaCalendarDay,
  FaChartLine,
  FaCheck,
  FaChevronLeft,
  FaChevronRight,
  FaClipboardList,
  FaClock,
  FaEdit,
  FaEnvelope,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaEye,
  FaFacebookF,
  FaFilter,
  FaGavel,
  FaGlobe,
  FaHandshake,
  FaHeart,
  FaHome,
  FaImage,
  FaInstagram,
  FaLandmark,
  FaLinkedinIn,
  FaList,
  FaListAlt,
  FaMapMarked,
  FaMapMarkerAlt,
  FaMoneyBillWave,
  FaPaperPlane,
  FaPhone,
  FaPlus,
  FaReact,
  FaRedo,
  FaRulerCombined,
  FaSearch,
  FaSearchDollar,
  FaShare,
  FaShieldAlt,
  FaSignOutAlt,
  FaSnapchatGhost,
  FaStar,
  FaTag,
  FaTimes,
  FaTrash,
  FaTwitter,
  FaUser,
  FaUsers,
  FaWhatsapp,
  FaYoutube,
  FaTiktok,
  FaFileContract,

  // FI
  FiBriefcase,
  FiCheckCircle,
  FiClock,
  FiDollarSign,
  FiFileText,
  FiHome,
  FiMail,
  FiPhone,
  FiUser,
  FiXCircle,

  // MD
  MdAssignment,
  MdBadge,
  MdBusiness,
  MdPerson,
  FaUpload, 
  FaFileAlt,
  FaBan,
  FaRegClock,
  FaRegFileAlt,
  FiArrowRight,
  FiLogIn,
  FiLock, FiEye, FiEyeOff, FiX, FiArrowLeft,
  FiFile, FiBook,
  FiCheck
};

export default Icons;
