// Font Awesome Icons
import {
  FaArrowLeft,
  FaArrowRight,
  FaAward,
  FaBell,
  FaBookmark,
  FaBriefcase,
  FaBuilding,
  FaBullhorn,
  FaBullseye,
  FaCalendarAlt,
  FaCalendarDay,
  FaChartLine,
  FaCheck,
  FaChevronLeft,
  FaChevronRight,
  FaClipboardList,
  FaClock,
  FaEdit,
  FaEnvelope,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaEye,
  FaFacebookF,
  FaFilter,
  FaGavel,
  FaGlobe,
  FaHandshake,
  FaHeart,
  FaHome,
  FaImage,
  FaInstagram,
  FaLandmark,
  FaLinkedinIn,
  FaList,
  FaListAlt,
  FaMapMarked,
  FaMapMarkerAlt,
  FaMoneyBillWave,
  FaPaperPlane,
  FaPhone,
  FaPlus,
  FaReact,
  FaRedo,
  FaRulerCombined,
  FaSearch,
  FaSearchDollar,
  FaShare,
  FaShieldAlt,
  FaSignOutAlt,
  FaSnapchatGhost,
  FaStar,
  FaTag,
  FaTimes,
  FaTrash,
  FaTwitter,
  FaUser,
  FaUsers,
  FaWhatsapp,
  FaYoutube,
  FaTiktok,
  FaFileContract,
  FaGem,
  FaCrown,
  FaBrain,
  FaNetworkWired,
  FaCheckCircle,
  FaUpload,
  FaFileAlt,
  FaBan,
  FaRegClock,
  FaRegFileAlt,
  // 🔹 الأيقونات الجديدة التي تحتاجها
  FaSpinner,        // أيقونة التحميل
  FaRegHeart,       // أيقونة القلب الفارغ
  FaCalendarCheck,  // أيقونة التقويم مع علامة صح
  FaLock,           // أيقونة القفل
  FaFire,           // أيقونة النار
  FaQuestionCircle, // أيقونة علامة الاستفهام
  // 🔹 إضافة أيقونات إضافية موجودة في LandCard       // (مكرر للتأكد) - القلب الفارغ
} from "react-icons/fa";

// Feather Icons
import {
  FiBriefcase,
  FiCheckCircle,
  FiClock,
  FiDollarSign,
  FiFileText,
  FiHome,
  FiMail,
  FiPhone,
  FiUser,
  FiArrowRight,
  FiLogIn,
  FiXCircle,
  FiLock, FiEye, FiEyeOff, FiX, FiArrowLeft,
  FiFile, FiBook,
  FiCheck
} from "react-icons/fi";

// Material Design Icons
import {
  MdAssignment,
  MdBadge,
  MdBusiness,
  MdPerson
} from "react-icons/md";

// 🔹 تصدير جميع الأيقونات في Object واحد
const Icons = {
  // FA
  FaCheckCircle,
  FaGem,
  FaCrown,
  FaBrain,
  FaNetworkWired,
  FaArrowLeft,
  FaArrowRight,
  FaAward,
  FaBell,
  FaBookmark,
  FaBriefcase,
  FaBuilding,
  FaBullhorn,
  FaBullseye,
  FaCalendarAlt,
  FaCalendarDay,
  FaChartLine,
  FaCheck,
  FaChevronLeft,
  FaChevronRight,
  FaClipboardList,
  FaClock,
  FaEdit,
  FaEnvelope,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaEye,
  FaFacebookF,
  FaFilter,
  FaGavel,
  FaGlobe,
  FaHandshake,
  FaHeart,
  FaHome,
  FaImage,
  FaInstagram,
  FaLandmark,
  FaLinkedinIn,
  FaList,
  FaListAlt,
  FaMapMarked,
  FaMapMarkerAlt,
  FaMoneyBillWave,
  FaPaperPlane,
  FaPhone,
  FaPlus,
  FaReact,
  FaRedo,
  FaRulerCombined,
  FaSearch,
  FaSearchDollar,
  FaShare,
  FaShieldAlt,
  FaSignOutAlt,
  FaSnapchatGhost,
  FaStar,
  FaTag,
  FaTimes,
  FaTrash,
  FaTwitter,
  FaUser,
  FaUsers,
  FaWhatsapp,
  FaYoutube,
  FaTiktok,
  FaFileContract,
  FaUpload,
  FaFileAlt,
  FaBan,
  FaRegClock,
  FaRegFileAlt,
  
  // 🔹 الأيقونات الجديدة المضافة
  FaSpinner,         // ✅ جديد
  FaRegHeart,        // ✅ جديد
  FaCalendarCheck,   // ✅ جديد
  FaLock,            // ✅ جديد
  FaFire,            // ✅ جديد
  FaQuestionCircle,  // ✅ جديد

  // FI
  FiBriefcase,
  FiCheckCircle,
  FiClock,
  FiDollarSign,
  FiFileText,
  FiHome,
  FiMail,
  FiPhone,
  FiUser,
  FiXCircle,
  FiArrowRight,
  FiLogIn,
  FiLock, FiEye, FiEyeOff, FiX, FiArrowLeft,
  FiFile, FiBook,
  FiCheck,

  // MD
  MdAssignment,
  MdBadge,
  MdBusiness,
  MdPerson,
};

export default Icons;